apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: article-service
  name: article-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: article-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: article-service
    spec:
      containers:
      - image: hipravin/devcompanion-article-service:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: devcompanion-article-service
#        resources: {}
        resources:
          limits:
            memory: 512Mi
#            cpu: #never set cpu limits!
          requests:
            memory: 512Mi
            cpu: "1000m"
        volumeMounts:
          - name: article-repo
            mountPath: /usr/local/article-repo
        env:
          - name: ARTICLES_REPO_PATH
            value: "/usr/local/article-repo"
          - name: JAVA_TOOL_OPTIONS
            value: "-Xmx256m"
          - name: KEYCLOAK_URL
#            value: "http://keycloak.hipravin.ru:8080"
            value: "http://host.docker.internal:8080"
          - name: REPO_SERVICE_URL
            value: "http://repo-service:8182"
          - name: ADMIN_SERVER_URL
            value: "http://admin:8070"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MANAGEMENT_BASE_URL
            value: "http://$(POD_IP):8083"
          - name: ADMIN_SERVER_USERNAME
            valueFrom:
              secretKeyRef:
                name: boot-admin-secret
                key: username
          - name: ADMIN_SERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: boot-admin-secret
                key: password

#          - name: MONGO_DATABASE   #FYI, switch to secretKeyRef
#            valueFrom:
#              configMapKeyRef:
#                name: mongodb
#                key: database-name

#       https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

        startupProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8083
          failureThreshold: 30
          periodSeconds: 10
          initialDelaySeconds: 30
#          #default 3
#          failureThreshold: 5
#          #default 10
#          periodSeconds: 15
#          #default 0
#          initialDelaySeconds: 30
#          #default 1
#          timeoutSeconds: 5

        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8083
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8083
      volumes:
        - name: article-repo
          persistentVolumeClaim:
            claimName: article-repo-pv-claim

status: {}
