apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: admin
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: admin
    spec:
      containers:
      - image: hipravin/devcompanion-admin:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: devcompanion-admin
        resources: {}
status: {}
