server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true

###
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
  thymeleaf:
    cache: false

  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL}
        username: ${ADMIN_SERVER_USERNAME}
        password: ${ADMIN_SERVER_PASSWORD}
        instance:
          management-base-url: ${MANAGEMENT_BASE_URL}

#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: ${GITHUB_CLIENT_ID}
#            client-secret: ${GITHUB_CLIENT_SECRET}

###
###
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    loggers:
      enabled: true
  server:
    port: 8081

---
spring:
  config:
    activate:
      on-profile: local

  boot:
    admin:
      client:
        url: http://localhost:8070
        username: admin
        password: admin
        instance:
          management-base-url: http://localhost:8081

app:
  routes:
    article-service-uri: "http://localhost:8082"


---
spring:
  config:
    activate:
      on-profile: docker

app:
  routes:
    article-service-uri: "http://article-service:8082"
