server:
  port: 8000

###
spring:
  application:
    name: gateway

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: devcompanion
#            client-secret: devcompanion-keycloak-secret  #if client set to 'confidential' in admin console
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL}/auth/realms/HiRealm
  cloud:
    gateway:
      routes:
        - id: article-service
          uri: ${ARTICLE_SERVICE_URI}
          predicates:
            - Path=/api/v1/articles/**
          filters:
            - TokenRelay=
        - id: frontend
          uri: ${FRONTEND_URI}
          predicates:
            - Path=/**

  thymeleaf:
    cache: false

  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL}
        username: ${ADMIN_SERVER_USERNAME}
        password: ${ADMIN_SERVER_PASSWORD}
        instance:
          management-base-url: ${MANAGEMENT_BASE_URL}

###
###
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    loggers:
      enabled: true
  server:
    port: 8002

---
spring:
  config:
    activate:
      on-profile: local

  boot:
    admin:
      client:
        url: http://localhost:8070
        username: admin
        password: admin
        instance:
          management-base-url: http://localhost:8081

ARTICLE_SERVICE_URI: "http://localhost:8082"
FRONTEND_URI: "http://localhost:3000"
KEYCLOAK_URL: "http://keycloak.hipravin.ru:8080"

#---
#spring:
#  config:
#    activate:
#      on-profile: docker
#
#app:
#  routes:
#    article-service-uri: "http://article-service:8082"
