server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true

###
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
  thymeleaf:
    cache: false
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: ${GITHUB_CLIENT_ID}
#            client-secret: ${GITHUB_CLIENT_SECRET}

###
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  server:
    port: 8081

---
spring:
  config:
    activate:
      on-profile: local

app:
  routes:
    article-service-uri: "http://localhost:8082"

---
spring:
  config:
    activate:
      on-profile: docker

app:
  routes:
    article-service-uri: "http://article-service:8082"
