server:
  port: 8000

#  servlet:
#    session:
#      timeout: 1m #short-lived session for testing
#      timeout: 1440m #24h long-lived session for testing

###
spring:
  application:
    name: gateway

  session:
    store-type: ${SESSION_STORE_PROVIDER} #redis|none
  redis:
    host: ${REDIS_HOST}
    port: 6379

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: devcompanion
#            client-secret: devcompanion-keycloak-secret  #if client set to 'confidential' in admin console
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL}/auth/realms/HiRealm

  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL}
        username: ${ADMIN_SERVER_USERNAME}
        password: ${ADMIN_SERVER_PASSWORD}
        instance:
          management-base-url: ${MANAGEMENT_BASE_URL}

app:
  routes:
    article-service-uri: ${ARTICLE_SERVICE_URI}
    repo-service-uri: ${REPO_SERVICE_URI}
    repo-service-auth-encoded: "dXNlcjp1dXNlcg=="
    frontend-uri: ${FRONTEND_URI}

###
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
      probes:
        enabled: true
    loggers:
      enabled: true
  server:
    port: 8002

