call kubectl apply -f .\secrets\boot-admin-secret.yml
call kubectl apply -f .\secrets\repo-db-secret.yml
call kubectl apply -f .\article\article-repo-pv.yml
call kubectl apply -f .\article\article-repo-pv-claim.yml
call kubectl apply -f .\article\article-service-deployment.yml
call kubectl apply -f .\article\article-service.yml
call kubectl apply -f .\repo-service-deployment.yml
call kubectl apply -f .\repo-service.yml
call kubectl apply -f .\gateway-deployment.yml
call kubectl apply -f .\gateway-service.yml
call kubectl apply -f .\devcompanion-ui-deployment.yml
call kubectl apply -f .\devcompanion-ui-service.yml
call kubectl apply -f .\admin\admin-deployment.yml
call kubectl apply -f .\admin\admin-service.yml
call kubectl apply -f .\ingress\devcompanion-tls.yml
call kubectl apply -f .\ingress\ingress.yml
