apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: devcompanion-ui
  name: devcompanion-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devcompanion-ui
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devcompanion-ui
    spec:
      containers:
      - image: hipravin/devcompanion-ui:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: devcompanion-ui
        resources: {}
status: {}
