apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gateway
  name: gateway
spec:
  replicas: 2
#  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gateway
    spec:
      containers:
      - image: hipravin/devcompanion-gateway:latest
        imagePullPolicy: IfNotPresent
        name: devcompanion-gateway

#        resources: {}
        resources:
          limits:
            memory: 512Mi
#            cpu: 4
          requests:
            memory: 512Mi
#            cpu: 1
        env:
          - name: JAVA_TOOL_OPTIONS
            value: "-Xmx256m"
          - name: SESSION_STORE_PROVIDER
            value: "redis"
#            value: "none"
          - name: REDIS_HOST
            value: "host.docker.internal"
          - name: KEYCLOAK_URL
#            value: "http://keycloak.hipravin.ru:8080"
            value: "http://host.docker.internal:8080"
          - name: ARTICLE_SERVICE_URI
            value: "http://article-service:8082"
          - name: FRONTEND_URI
            value: "http://devcompanion-ui:3000"
          - name: ADMIN_SERVER_URL
            value: "http://admin:8070"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MANAGEMENT_BASE_URL
            value: "http://$(POD_IP):8002"
          - name: ADMIN_SERVER_USERNAME
            valueFrom:
              secretKeyRef:
                name: boot-admin-secret
                key: username
          - name: ADMIN_SERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: boot-admin-secret
                key: password

        startupProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8002
          failureThreshold: 30
          periodSeconds: 10
          initialDelaySeconds: 30

        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8002

        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8002

status: {}
