spring:
  config:
    activate:
      on-profile: local

  boot:
    admin:
      client:
        enabled: false
#        url: http://localhost:8070
#        username: admin
#        password: admin
#        instance:
#          management-base-url: http://localhost:8083

logging:
  level:
    org.springframework: DEBUG
    org.springframework.security: TRACE

springdoc:
  swagger-ui:
    enabled: true

###
ARTICLES_REPO_PATH: "C:/dev/projects/devcompanion/article-repo"
KEYCLOAK_URL: "http://host.docker.internal:8080"
REPO_SERVICE_URL: "http://localhost:8182/"
