application:
  articles-max-response-limit: 1000
  articles-default-response-limit: 20

  acticles-yaml-path: ${ARTICLES_REPO_PATH}

  ## to disable swagger ui on prod
  #springdoc:
  #  swagger-ui:
  #    enabled: false

---
spring:
  config:
    activate:
      on-profile: local

application:
  acticles-yaml-path: C:/dev/projects/devcompanion/articles-repo

