server:
  port: 8082
  tomcat:
    accesslog:
      enabled: true

spring:
  application:
    name: article-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/auth/realms/HiRealm
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL}
        username: ${ADMIN_SERVER_USERNAME}
        password: ${ADMIN_SERVER_PASSWORD}
        instance:
          management-base-url: ${MANAGEMENT_BASE_URL}


###
application:
  articles-max-response-limit: 1000
  articles-default-response-limit: 20
  acticles-yaml-path: ${ARTICLES_REPO_PATH}

repo-service:
  url: ${REPO_SERVICE_URL}
  user:
    name: user
    password: uuser

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

###
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    loggers:
      enabled: true
  server:
    port: 8083

###
#disable openapi
springdoc:
  swagger-ui:
    enabled: false