spring:
  application:
    name: article-service

server:
  port: 8082

application:
  articles-max-response-limit: 1000
  articles-default-response-limit: 20

  acticles-yaml-path: ${ARTICLES_REPO_PATH}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8083

---
spring:
  config:
    activate:
      on-profile: local

application:
  acticles-yaml-path: C:/dev/projects/devcompanion/articles-repo

---
spring:
  config:
    activate:
      on-profile: docker

springdoc:
  swagger-ui:
    enabled: false
