spring:
  application:
    name: article-service

server:
  port: 8082

  tomcat:
    accesslog:
      enabled: true

application:
  articles-max-response-limit: 1000
  articles-default-response-limit: 20

  acticles-yaml-path: ${ARTICLES_REPO_PATH}

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      probes:
        enabled: true

  server:
    port: 8083


---
spring:
  config:
    activate:
      on-profile: local

application:
  acticles-yaml-path: C:/dev/projects/devcompanion/article-repo


---
spring:
  config:
    activate:
      on-profile: docker

springdoc:
  swagger-ui:
    enabled: false
