server:
  port: 8070

spring:
  security:
    user:
      name: admin
      password: admin

  boot:
    admin:
      client:
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}

      instance-auth:
        enabled: true
        service-map:
          article-service.user-name: admin
          article-service.user-password: aadmin
          repo-service.user-name: admin
          repo-service.user-password: aadmin